version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosq_data:/mosquitto/data
      - mosq_log:/mosquitto/log
volumes:
  mosq_data:
  mosq_log:
